CREATE TABLE Cards (
 Id INT NOT NULL AUTO_INCREMENT,
 Name NVARCHAR(255) NOT NULL,
 Cost NVARCHAR(100) NOT NULL,
 Type NVARCHAR(255) NOT NULL,
 Effect TEXT,
 Power NVARCHAR(16) NOT NULL,
 Toughness NVARCHAR(16) NOT NULL,
 Rarity NVARCHAR(10) NOT NULL,
 ConvertedManaCost INT NOT NULL,
 NumberOwned INT NOT NULL,
 PRIMARY KEY (Id)
);
